import { Plus_Jakarta_Sans, Lato, Playfair_Display } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
// Vercel Web Analytics component removed in V1 — it 404s on
// /_vercel/insights/script.js until Analytics is enabled on the
// project via the Vercel dashboard (billed feature). GA4 below
// covers V1 tracking. To re-enable: toggle Web Analytics in the
// simplworks-ai Vercel project, then restore:
//   import { Analytics } from '@vercel/analytics/react';
//   <Analytics /> inside <body>.

/**
 * Font weights are trimmed to what the CSS and JSX actually reference.
 * Audit source: every font-weight declaration in globals.css + every
 * fontWeight in JSX. Split into normal/italic imports so the Cartesian
 * product doesn't pull in unused italic variants.
 *
 * Plus Jakarta: 700, 800 normal only (no italic used anywhere).
 * Lato: 400/700 normal, 400 italic only. Google Fonts Lato ships
 *   100/300/400/700/900 — weight 500 (.ticker-item) is rendered by
 *   the browser as nearest loaded weight (400 per CSS spec rules),
 *   same as before this trim.
 * Playfair: 400/700 normal, 400 italic only (700 italic unused).
 */
const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['700', '800'],
  variable: '--font-display',
  display: 'swap',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: 'normal',
  variable: '--font-body',
  // 'optional' instead of 'swap': browser uses Next.js's metric-adjusted
  // fallback font if Lato doesn't download within ~100ms, and does NOT
  // swap mid-render on first visit. This lets Chrome fire LCP at the
  // fallback paint (~1.3s) rather than waiting for the Lato swap (~2.8s).
  // Lato still loads in the background and serves from cache on return
  // visits, so repeat visitors get full Lato immediately. The hero-sub
  // paragraph is the LCP element and renders in var(--font-body), so
  // this is the direct lever for mobile LCP.
  display: 'optional',
});

const latoItalic = Lato({
  subsets: ['latin'],
  weight: '400',
  style: 'italic',
  variable: '--font-body-italic',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: 'normal',
  variable: '--font-wordmark',
  display: 'swap',
});

const playfairItalic = Playfair_Display({
  subsets: ['latin'],
  weight: '400',
  style: 'italic',
  variable: '--font-wordmark-italic',
  display: 'swap',
});

const DESCRIPTION =
  'SimplWorks builds custom websites by hand, one at a time. Built by hand from scratch by Stephanie Belote with SEO, AEO, and GEO built in. Knoxville, TN. Delivered in about a week.';

export const metadata = {
  metadataBase: new URL('https://simplworks.ai'),
  title: 'SimplWorks — Custom Websites Built by Hand | Knoxville, TN',
  description: DESCRIPTION,
  keywords: [
    'custom website design',
    'handbuilt websites',
    'AI-optimized websites',
    'SEO',
    'AEO',
    'GEO',
    'Knoxville web designer',
    'Tennessee web designer',
    'conversion websites',
    'SimplWorks',
    'Stephanie Belote',
    'friction audit',
  ],
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'SimplWorks — Custom Websites Built by Hand',
    description: DESCRIPTION,
    url: '/',
    siteName: 'SimplWorks',
    locale: 'en_US',
    type: 'website',
    // og:image auto-wired by app/opengraph-image.js
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SimplWorks — Custom Websites Built by Hand',
    description: DESCRIPTION,
    // twitter:image auto-wired by app/opengraph-image.js
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} ${lato.variable} ${latoItalic.variable} ${playfair.variable} ${playfairItalic.variable}`}
    >
      <head>
        {/* favicon + apple-touch-icon auto-generated by app/icon.js and app/apple-icon.js */}
        {/* Preconnect to GA4 hosts so the script + beacon don't stall on TLS handshake.
            googletagmanager.com serves gtag.js; google-analytics.com receives the
            measurement beacon. Preconnecting both recovers ~375ms on mobile LCP
            per Lighthouse. Property ID G-2QP0NN6B5X (account shopaikidos@gmail.com). */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://www.google-analytics.com" />
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2QP0NN6B5X"
          strategy="lazyOnload"
        />
        <Script id="google-analytics" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2QP0NN6B5X');
          `}
        </Script>
        {/* Delegated click + toggle tracking for conversion-adjacent events.
            Lives as a single document-level listener so server components
            (ReachMe, Faq) stay server-rendered. */}
        <Script id="ga-custom-events" strategy="afterInteractive">
          {`
            (function() {
              if (typeof document === 'undefined') return;
              document.addEventListener('click', function(e) {
                if (typeof gtag !== 'function') return;
                var insider = e.target.closest && e.target.closest('.insider-btn');
                if (insider) {
                  gtag('event', 'insider_open', { event_category: 'engagement' });
                }
                var audit = e.target.closest && e.target.closest('a[href^="mailto:stephanie@simplworks.ai"]');
                if (audit) {
                  gtag('event', 'friction_audit_email', { event_category: 'conversion' });
                }
              });
              document.addEventListener('toggle', function(e) {
                if (typeof gtag !== 'function') return;
                var t = e.target;
                if (!t || !t.matches || !t.matches('.faq-item') || !t.open) return;
                var q = t.querySelector('.faq-question');
                gtag('event', 'faq_expand', {
                  event_category: 'engagement',
                  event_label: q ? q.textContent.trim() : 'unknown'
                });
              }, true);
            })();
          `}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
