import { Plus_Jakarta_Sans, Lato, Playfair_Display } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
// Vercel Web Analytics component removed in V1 — it 404s on
// /_vercel/insights/script.js until Analytics is enabled on the
// project via the Vercel dashboard (billed feature). GA4 below
// covers V1 tracking. To re-enable: toggle Web Analytics in the
// simplworks-ai Vercel project, then restore:
//   import { Analytics } from '@vercel/analytics/react';
//   <Analytics /> inside <body>.

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
  variable: '--font-display',
  display: 'swap',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-body',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-wordmark',
  display: 'swap',
});

const DESCRIPTION =
  'SimplWorks builds custom websites by hand, one at a time. Coded from scratch by Stephanie Belote with SEO, AEO, and GEO built in. Knoxville, TN. Delivered in about a week.';

export const metadata = {
  metadataBase: new URL('https://simplworks.ai'),
  title: 'SimplWorks — Custom Websites Built by Hand | Knoxville, TN',
  description: DESCRIPTION,
  keywords: [
    'custom website design',
    'handbuilt websites',
    'AI-optimized websites',
    'SEO',
    'AEO',
    'GEO',
    'Knoxville web designer',
    'Tennessee web designer',
    'conversion websites',
    'SimplWorks',
    'Stephanie Belote',
    'friction audit',
  ],
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'SimplWorks — Custom Websites Built by Hand',
    description: DESCRIPTION,
    url: '/',
    siteName: 'SimplWorks',
    locale: 'en_US',
    type: 'website',
    // og:image auto-wired by app/opengraph-image.js
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SimplWorks — Custom Websites Built by Hand',
    description: DESCRIPTION,
    // twitter:image auto-wired by app/opengraph-image.js
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} ${lato.variable} ${playfair.variable}`}
    >
      <head>
        {/* favicon + apple-touch-icon auto-generated by app/icon.js and app/apple-icon.js */}
        {/* Preconnect to GA4 host so the script request doesn't stall on TLS handshake */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2QP0NN6B5X"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2QP0NN6B5X');
          `}
        </Script>
        {/* Delegated click + toggle tracking for conversion-adjacent events.
            Lives as a single document-level listener so server components
            (ReachMe, Faq) stay server-rendered. */}
        <Script id="ga-custom-events" strategy="afterInteractive">
          {`
            (function() {
              if (typeof document === 'undefined') return;
              document.addEventListener('click', function(e) {
                if (typeof gtag !== 'function') return;
                var insider = e.target.closest && e.target.closest('.insider-btn');
                if (insider) {
                  gtag('event', 'insider_open', { event_category: 'engagement' });
                }
                var audit = e.target.closest && e.target.closest('a[href^="mailto:stephanie@simplworks.ai"]');
                if (audit) {
                  gtag('event', 'friction_audit_email', { event_category: 'conversion' });
                }
              });
              document.addEventListener('toggle', function(e) {
                if (typeof gtag !== 'function') return;
                var t = e.target;
                if (!t || !t.matches || !t.matches('.faq-item') || !t.open) return;
                var q = t.querySelector('.faq-question');
                gtag('event', 'faq_expand', {
                  event_category: 'engagement',
                  event_label: q ? q.textContent.trim() : 'unknown'
                });
              }, true);
            })();
          `}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
